### ISSUE TITLE
Full History Planet no longer experimental

### ISSUE THREAD

**Issue by nrenner** [MaZderMind/osm-history-splitter#15]
The Full History Planet [switched location](http://wiki.openstreetmap.org/w/index.php?title=Planet.osm%2Ffull&diff=1014354&oldid=998427) a while ago and is [updated weekly](https://twitter.com/OSM_Tech/status/547050650635603970). The [experimental](http://planet.osm.org/planet/experimental/?C=N;O=A) files are no longer updated - and neither are your [extracts](http://osm.personalwerk.de/full-history-extracts/) because of that?

The following links (others?) would need to be updated to
http://planet.osm.org/planet/full-history/

* [fetch-and-split.php](https://github.com/MaZderMind/osm-history-splitter/blob/e496e375a3080351b86c968661f90dc3f2c626b0/tools/fetch-and-split.php#L10)
* "full-planet-full-history pbf" in [TUTORIAL.md](https://github.com/MaZderMind/osm-history-renderer/blob/cd22334670da1a91612b9e040821f97c7cc2ed07/TUTORIAL.md#cutting-your-area)

**Comment by MaZderMind** [comment]
I don't provide hosted Extracts anymore because I just didn't bother… I'm working on different things now. I updated the Tutorial. Thank you for the Pointer.
