### ISSUE TITLE
redirection to libosm-port might break the tool

### ISSUE THREAD

**Issue by tobwen** [MaZderMind/osm-history-splitter#17]
I've found a bug in https://github.com/joto/osm-history-splitter/issues/1
Jochen explained that his version hasn't been tested pretty well and it was only a quick port to libosmium.

Maybe you shouldn't tell new users to use Joto's port until it has been fixed. Your version is working (better?) right now.

**Comment by kcwu** [comment]
+1 I were trying to migrate and found the new one doesn't work after wasted half hours.
