### ISSUE TITLE
libosmium make

### ISSUE THREAD

**Issue by moll734** [MaZderMind/osm-history-splitter#18]
I have been trying to install osm-history-splitter for 2 weeks. I cannot seem to get past the following message:

mike@mike-VirtualBox:~/osm-history-splitter/libosmium/build$ make
make: *** No targets specified and no makefile found. Stop.

Where am I going wrong?

Thanks

**Comment by MaZderMind** [comment]
Please read https://github.com/MaZderMind/osm-history-splitter/blob/master/CONTRIBUTING.md on why I'm closing this ticket.
