### ISSUE TITLE
make: osm-history-splitter

### ISSUE THREAD

**Issue by moll734** [MaZderMind/osm-history-splitter#19]
Hi - I am using Ubunto to run OSM-History-Splitter. Libosmium and dependencies have been added and built. All appears to run without issue until I make osm-history-splitter.

I get the following error:

mike@mike-VirtualBox:~/osm-history-splitter$ make
[ 50%] Building CXX object CMakeFiles/osm-history-splitter.dir/splitter.cpp.o
/home/mike/osm-history-splitter/splitter.cpp:9:35: fatal error: osmium/io/any_input.hpp: No such file or directory
compilation terminated.
CMakeFiles/osm-history-splitter.dir/build.make:62: recipe for target 'CMakeFiles/osm-history-splitter.dir/splitter.cpp.o' failed
make[2]: *** [CMakeFiles/osm-history-splitter.dir/splitter.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/osm-history-splitter.dir/all' failed
make[1]: *** [CMakeFiles/osm-history-splitter.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MaZderMind** [comment]
Please read https://github.com/MaZderMind/osm-history-splitter/blob/master/CONTRIBUTING.md on why I'm closing this ticket.
