### ISSUE TITLE
fatal error when build the application use make

### ISSUE THREAD

**Issue by tongjiyiming** [MaZderMind/osm-history-splitter#20]
Got this error:

splitter.cpp:13:10: fatal error: 'osmium.hpp' file not found
#include <osmium.hpp>
         ^
1 error generated.

Do you know what is the problem?

**Comment by MaZderMind** [comment]
Please read https://github.com/MaZderMind/osm-history-splitter/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-issues-with-the-software
