### ISSUE TITLE
Stuck at opening writer

### ISSUE THREAD

**Issue by themmes** [MaZderMind/osm-history-splitter#21]
Hi Peter,

So far so good, got all the dependencies set up and your splitter running.

Trying to split `history-latest.osm.bz2` into a `history-north-america.osm.bz2` using the .poly from Geofabrik. However the splitter seems to be stuck at opening the writer. Is there something I am missing?

config
`/data/osm/history-north-america.osm.bz2 POLY    /home/tom/north-america.poly`

**Comment by themmes** [comment]
By the way, I noticed you advise to use the `pbf` filetype, however using the `history-latest.osm.pbf` returned an filetype error from the osmium library for me.

**Comment by joto** [comment]
@themmes I recommend using [osmium-tool](http://osmcode.org/osmium-tool/) instead. Its [`extract`](http://docs.osmcode.org/osmium/latest/osmium-extract.html) command can do extracts faster then osm-history-splitter and it is still maintained.

**Comment by themmes** [comment]
Oh that's great, sorry, from the documentation I figured the `osm-history-splitter` was the only right tool for the job. Thank you!
